version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/my-app/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/contracts/' 
    schedule:
      interval: 'daily'
